"""Errorz Barz -- world/pop/hip-hop drum patterns from Paul Wenzel's
"Pocket Operations" booklet: 246 patterns across 21 genre sections,
each a 16-step grid.

This is the raw transcription: which instrument hits which step, and
nothing about Uncertainty's gate channels -- that mapping lives in
gate_mapping.py, kept separate so this file stays a plain, reusable
record of the book's content.

TERMS
    pattern    A single 16-step drum sequence. Some patterns are meant
               to be chained ("A" into "B", sometimes into "C"/"D"/"E")
               to make a longer phrase -- see `variant` below.
    instrument A single drum/percussion voice, one of 12 possible codes:
                   BD  Bass Drum      SN  Snare        LT  Low Tom
                   MT  Medium Tom     HT  High Tom      CL  Hand Clap
                   SH  Shaker         RS  Rimshot       CB  Cowbell
                   CY  Cymbal         OH  Open Hi-Hat    CH  Closed Hi-Hat
               (The book also uses "HC" in a few sections as an alternate
               spelling of Hand Clap; normalized to CL here since the two
               never appear in the same pattern.)
    step       One 16th of the measure (1-16). Every pattern here is
               exactly 16 steps.
    accent     A step marked for emphasis, independent of which
               instrument(s) hit there.

DATA STRUCTURES
    PATTERNS      One dict per pattern:
                      section   genre/chapter name, e.g. "Rock", "House"
                      name      pattern title, chain suffix stripped
                      variant   'A'/'B'/'C'/'D'/'E' if this is one part of
                                a chained sequence, else None
                      rows      {instrument_code: [step, step, ...]} --
                                only instruments that are actually used
                                appear as keys
                      accents   [step, step, ...] -- which steps are
                                accented, regardless of instrument
    PATTERN_NOTES Per-pattern notes for known data quirks that would
                  otherwise look like self-test failures -- see below.

CLEANUP FROM THE RAW EXTRACTION
    The book (259 patterns after dropping its intro's illustrative
    example) had 13 pairs/triples of patterns that were EXACT duplicates
    of each other under a different name -- same rows, same accents,
    just filed under two genres or chained differently. Those were
    collapsed to one entry each, down to 246 total. This wasn't just
    tidiness: with 8 gate outputs and a binary pattern-index readout
    (see code.py), 246 comfortably fits inside 8 bits (max 256 values),
    where 259 would not have.

    "The Groove - B" originally had its Shaker part folded into Medium
    Tom, back when gate_mapping.py only had 5 dynamic "flex" channels
    and this pattern needed a 6th. That constraint is gone now that
    every instrument has its own fixed channel (see gate_mapping.py),
    so the fold was undone -- Shaker and Medium Tom are separate rows
    again here, matching the book.

Run this file directly (`python patterns.py`) to self-test: every row
and accent step should fall within 1-16, and every floating accent (one
with no instrument hit on the same step) should have a PATTERN_NOTES
entry explaining it.

Source: Paul Wenzel, "Pocket Operations" (Second Edition, Rev. 3.1,
        2024). (c) 2024 Paul Wenzel, some rights reserved -- intended
        for educational use; see this project's README for the exact
        wording. Free copies at https://shittyrecording.studio
Built by: Claude (Sonnet) & cubbs, 2026.
"""

PATTERN_NOTES = {
    ("IN THE AIR LAST NIGHT", "A"): (
        "accent on step 5 has no drum hit there in this variant -- the B "
        "variant has a BD hit on step 5 and the same accent; looks like "
        "the accent row was copied from B to A without adjusting for A's "
        "sparser kick part. Kept as-is (accent still fires on step 5, "
        "just with no instrument channel alongside it)."
    ),
}


def pattern_key(p):
    """(name, variant) -- unique enough to key into PATTERN_NOTES."""
    return (p["name"], p["variant"])


PATTERNS = [
    {
        'section': 'Basic Patterns',
        'name': 'ONE AND SEVEN & FIVE AND THIRTEEN',
        'variant': None,
        'rows': {'BD': [1, 7], 'SN': [5, 13]},
        'accents': [],
    },
    {
        'section': 'Basic Patterns',
        'name': "BOOTS N' CATS",
        'variant': None,
        'rows': {'BD': [1, 9], 'SN': [5, 13], 'CH': [1, 3, 5, 7, 9, 11, 13, 15]},
        'accents': [],
    },
    {
        'section': 'Basic Patterns',
        'name': 'TINY HOUSE',
        'variant': None,
        'rows': {'BD': [1, 5, 9, 13], 'OH': [3, 7, 11, 15]},
        'accents': [],
    },
    {
        'section': 'Basic Patterns',
        'name': 'GOOD TO GO',
        'variant': None,
        'rows': {'BD': [1, 4, 7, 11], 'SN': [5, 13]},
        'accents': [],
    },
    {
        'section': 'Standard Breaks',
        'name': 'STANDARD BREAK 1',
        'variant': None,
        'rows': {'BD': [1, 11], 'SN': [5, 13], 'CH': [1, 3, 5, 7, 9, 10, 11, 13, 15]},
        'accents': [],
    },
    {
        'section': 'Standard Breaks',
        'name': 'STANDARD BREAK 2',
        'variant': None,
        'rows': {'BD': [1, 11], 'SN': [5, 13], 'CH': [1, 3, 5, 7, 8, 9, 11, 15]},
        'accents': [],
    },
    {
        'section': 'Standard Breaks',
        'name': 'ROLLING BREAK',
        'variant': None,
        'rows': {'BD': [1, 8, 11], 'SN': [5, 13], 'CH': [1, 3, 5, 7, 9, 11, 13, 15]},
        'accents': [],
    },
    {
        'section': 'Standard Breaks',
        'name': 'THE UNKNOWN DRUMMER',
        'variant': None,
        'rows': {'BD': [1, 4, 7, 11], 'SN': [2, 5, 8, 13], 'OH': [9, 15], 'CH': [2, 3, 5, 6, 8, 14]},
        'accents': [5, 13],
    },
    {
        'section': 'Rock',
        'name': 'ROCK 1',
        'variant': None,
        'rows': {'BD': [1, 8, 9, 11], 'SN': [5, 13], 'CY': [1], 'CH': [1, 3, 5, 7, 9, 11, 13, 15]},
        'accents': [],
    },
    {
        'section': 'Rock',
        'name': 'ROCK 2',
        'variant': None,
        'rows': {'BD': [1, 8, 9, 11], 'SN': [5, 13], 'CH': [1, 3, 5, 7, 9, 11, 13, 15]},
        'accents': [],
    },
    {
        'section': 'Rock',
        'name': 'ROCK 3',
        'variant': None,
        'rows': {'BD': [1, 8, 9, 11], 'SN': [5, 13], 'OH': [15], 'CH': [1, 3, 5, 7, 9, 11, 13, 15]},
        'accents': [],
    },
    {
        'section': 'Rock',
        'name': 'ROCK 4',
        'variant': None,
        'rows': {'BD': [1, 8, 9, 11], 'SN': [5, 13, 15, 16], 'OH': [15], 'CH': [1, 3, 5, 7, 9, 11, 13, 15]},
        'accents': [],
    },
    {
        'section': 'Electro',
        'name': 'ELECTRO 1',
        'variant': 'B',
        'rows': {'BD': [1, 7, 11, 15], 'SN': [5, 13]},
        'accents': [],
    },
    {
        'section': 'Electro',
        'name': 'ELECTRO 2',
        'variant': 'B',
        'rows': {'BD': [1, 11, 14], 'SN': [5, 13]},
        'accents': [],
    },
    {
        'section': 'Electro',
        'name': 'ELECTRO 3',
        'variant': 'A',
        'rows': {'BD': [1, 7, 12], 'SN': [5, 13]},
        'accents': [],
    },
    {
        'section': 'Electro',
        'name': 'ELECTRO 3',
        'variant': 'B',
        'rows': {'BD': [1, 7, 12, 14], 'SN': [5, 13]},
        'accents': [],
    },
    {
        'section': 'Electro',
        'name': 'ELECTRO 4',
        'variant': None,
        'rows': {'BD': [1, 7, 11, 14], 'SN': [5, 13]},
        'accents': [],
    },
    {
        'section': 'Electro',
        'name': 'SIBERIAN NIGHTS',
        'variant': None,
        'rows': {'BD': [1, 7], 'SN': [5, 13], 'CH': [1, 3, 4, 5, 7, 8, 9, 11, 12, 13, 15, 16]},
        'accents': [],
    },
    {
        'section': 'Electro',
        'name': 'NEW WAVE',
        'variant': None,
        'rows': {'BD': [1, 7, 9, 10], 'SN': [5, 13], 'SH': [5, 13], 'OH': [3], 'CH': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16]},
        'accents': [],
    },
    {
        'section': 'House',
        'name': 'HOUSE 2',
        'variant': None,
        'rows': {'BD': [1, 5, 9, 13], 'SN': [5, 13], 'OH': [3, 6, 11, 14], 'CH': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16]},
        'accents': [],
    },
    {
        'section': 'House',
        'name': 'BRIT HOUSE',
        'variant': None,
        'rows': {'BD': [1, 5, 9, 13], 'CL': [5, 13], 'CY': [3, 7, 11, 15], 'OH': [3, 7, 11, 15], 'CH': [1, 2, 4, 5, 6, 8, 9, 10, 12, 13, 14, 16]},
        'accents': [],
    },
    {
        'section': 'House',
        'name': 'FRENCH HOUSE',
        'variant': None,
        'rows': {'BD': [1, 5, 9, 13], 'CL': [5, 13], 'SH': [1, 2, 3, 5, 7, 8, 9, 10, 11, 13, 15, 16], 'OH': [2, 4, 6, 8, 10, 12, 14, 16], 'CH': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16]},
        'accents': [],
    },
    {
        'section': 'House',
        'name': 'DIRTY HOUSE',
        'variant': None,
        'rows': {'BD': [1, 3, 5, 9, 11, 13, 16], 'SN': [5, 13], 'CL': [3, 5, 9, 11, 13], 'OH': [3, 11, 15], 'CH': [11, 16]},
        'accents': [3, 16],
    },
    {
        'section': 'House',
        'name': 'DEEP HOUSE',
        'variant': None,
        'rows': {'BD': [1, 5, 9, 13], 'CL': [5, 13], 'OH': [3, 7, 11, 15], 'CH': [2, 8, 10]},
        'accents': [],
    },
    {
        'section': 'House',
        'name': 'DEEPER HOUSE',
        'variant': None,
        'rows': {'BD': [1, 5, 9, 13], 'MT': [3, 8, 11], 'CL': [2, 10], 'SH': [4, 9], 'OH': [3, 7, 11, 12, 15]},
        'accents': [],
    },
    {
        'section': 'House',
        'name': 'SLOW DEEP HOUSE',
        'variant': None,
        'rows': {'BD': [1, 5, 9, 13], 'CL': [5, 13], 'SH': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16], 'OH': [3, 4, 7, 8, 10, 11, 13], 'CH': [1, 5, 9, 13]},
        'accents': [],
    },
    {
        'section': 'House',
        'name': 'FOOTWORK',
        'variant': 'A',
        'rows': {'BD': [1, 4, 7, 9, 12, 15], 'CL': [13], 'RS': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16], 'CH': [3, 11]},
        'accents': [],
    },
    {
        'section': 'House',
        'name': 'FOOTWORK',
        'variant': 'B',
        'rows': {'BD': [1, 4, 7, 9, 12, 15], 'CL': [13], 'RS': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16], 'CH': [3, 7, 8, 11, 15]},
        'accents': [],
    },
    {
        'section': 'Miami Bass',
        'name': 'MIAMI BASS',
        'variant': 'B',
        'rows': {'BD': [1, 7, 11, 14], 'SN': [5, 13], 'CH': [1, 3, 4, 5, 7, 8, 9, 11, 12, 13, 15, 16]},
        'accents': [],
    },
    {
        'section': 'Miami Bass',
        'name': 'SALLY',
        'variant': None,
        'rows': {'BD': [1, 7, 11, 15], 'SN': [5, 13], 'LT': [1, 7, 11, 15], 'CH': [1, 3, 5, 7, 9, 11, 13, 15]},
        'accents': [],
    },
    {
        'section': 'Miami Bass',
        'name': 'ROCK THE PLANET',
        'variant': None,
        'rows': {'BD': [1, 4, 7], 'SN': [5, 13], 'CH': [1, 3, 4, 5, 7, 8, 9, 11, 12, 13, 14, 15, 16]},
        'accents': [],
    },
    {
        'section': 'Hip Hop',
        'name': 'HIP HOP 1',
        'variant': 'A',
        'rows': {'BD': [1, 7, 8, 12, 15], 'SN': [5, 13]},
        'accents': [],
    },
    {
        'section': 'Hip Hop',
        'name': 'HIP HOP 1',
        'variant': 'B',
        'rows': {'BD': [1, 8, 12], 'SN': [5, 13]},
        'accents': [],
    },
    {
        'section': 'Hip Hop',
        'name': 'HIP HOP 2',
        'variant': 'A',
        'rows': {'BD': [1, 8, 9, 10, 14, 16], 'SN': [5, 13]},
        'accents': [],
    },
    {
        'section': 'Hip Hop',
        'name': 'HIP HOP 2',
        'variant': 'B',
        'rows': {'BD': [1, 8, 9, 12], 'SN': [5, 10, 13]},
        'accents': [],
    },
    {
        'section': 'Hip Hop',
        'name': 'HIP HOP 3',
        'variant': 'A',
        'rows': {'BD': [1, 3, 9, 11], 'SN': [5, 13]},
        'accents': [],
    },
    {
        'section': 'Hip Hop',
        'name': 'HIP HOP 3',
        'variant': 'B',
        'rows': {'BD': [1, 3, 9, 10, 12], 'SN': [5, 13]},
        'accents': [],
    },
    {
        'section': 'Hip Hop',
        'name': 'HIP HOP 4',
        'variant': 'A',
        'rows': {'BD': [1, 4, 8, 10, 11, 16], 'SN': [5, 13]},
        'accents': [],
    },
    {
        'section': 'Hip Hop',
        'name': 'HIP HOP 4',
        'variant': 'B',
        'rows': {'BD': [1, 3, 8, 9, 10, 11], 'SN': [5, 13]},
        'accents': [],
    },
    {
        'section': 'Hip Hop',
        'name': 'HIP HOP 5',
        'variant': None,
        'rows': {'BD': [1, 3, 8, 9, 11, 16], 'SN': [5, 13]},
        'accents': [],
    },
    {
        'section': 'Hip Hop',
        'name': 'HIP HOP 6',
        'variant': None,
        'rows': {'BD': [1, 3, 11, 12, 16], 'SN': [5, 13], 'CH': [1, 3, 5, 7, 9, 11, 13, 15]},
        'accents': [],
    },
    {
        'section': 'Hip Hop',
        'name': 'HIP HOP 7',
        'variant': None,
        'rows': {'BD': [1, 8, 11, 14, 16], 'SN': [5, 13], 'CH': [1, 3, 5, 7, 9, 11, 13, 15]},
        'accents': [],
    },
    {
        'section': 'Hip Hop',
        'name': 'HIP HOP 8',
        'variant': None,
        'rows': {'BD': [1, 4, 9, 11, 12], 'SN': [5, 13], 'OH': [6, 14], 'CH': [1, 2, 4, 5, 7, 8, 9, 10, 12, 13, 15, 16]},
        'accents': [],
    },
    {
        'section': 'Hip Hop',
        'name': 'TRAP',
        'variant': 'A',
        'rows': {'BD': [1, 7, 13], 'SN': [9], 'CH': [1, 3, 5, 7, 9, 11, 13, 15]},
        'accents': [],
    },
    {
        'section': 'Hip Hop',
        'name': 'TRAP',
        'variant': 'B',
        'rows': {'BD': [3, 5], 'SN': [9], 'CH': [3, 5, 7, 9, 11, 15]},
        'accents': [],
    },
    {
        'section': 'Hip Hop',
        'name': 'PLANET ROCK',
        'variant': 'A',
        'rows': {'BD': [1, 7], 'SN': [5, 13], 'CL': [5, 13], 'CB': [1, 3, 5, 7, 8, 10, 12, 13, 15], 'CH': [1, 3, 4, 5, 7, 8, 9, 11, 12, 13, 14, 15, 16]},
        'accents': [],
    },
    {
        'section': 'Hip Hop',
        'name': 'PLANET ROCK',
        'variant': 'B',
        'rows': {'BD': [1, 7, 11, 14], 'SN': [5, 13], 'CL': [5, 13], 'CB': [1, 3, 5, 7, 8, 10, 12, 13, 15], 'CH': [1, 3, 4, 5, 7, 8, 9, 11, 12, 13, 14, 15, 16]},
        'accents': [],
    },
    {
        'section': 'Hip Hop',
        'name': 'INNA CLUB',
        'variant': None,
        'rows': {'BD': [3, 8, 11, 16], 'SN': [5, 13], 'CL': [5, 13], 'OH': [1, 3, 5, 7, 9, 11, 13, 15]},
        'accents': [],
    },
    {
        'section': 'Hip Hop',
        'name': 'ICE',
        'variant': None,
        'rows': {'BD': [1, 7, 11, 15], 'SN': [5, 13], 'SH': [1, 3, 5, 7, 9, 11, 13, 15]},
        'accents': [],
    },
    {
        'section': 'Hip Hop',
        'name': 'BACK TO CALI',
        'variant': 'A',
        'rows': {'BD': [1, 7], 'SN': [5, 13], 'CL': [5, 7, 9, 13, 15], 'CH': [1, 3, 5, 7, 9, 11, 13, 15]},
        'accents': [],
    },
    {
        'section': 'Hip Hop',
        'name': 'BACK TO CALI',
        'variant': 'B',
        'rows': {'BD': [1, 7, 11, 14], 'SN': [5, 13], 'CL': [1, 5, 7, 9, 13], 'OH': [13], 'CH': [1, 3, 5, 7, 9, 11, 15]},
        'accents': [],
    },
    {
        'section': 'Hip Hop',
        'name': 'SNOOP STYLES',
        'variant': None,
        'rows': {'BD': [1, 4, 7, 11], 'SN': [5, 13], 'CL': [5, 13], 'RS': [3, 6, 9, 12], 'OH': [1, 4, 7, 11]},
        'accents': [],
    },
    {
        'section': 'Hip Hop',
        'name': 'THE GROOVE',
        'variant': 'A',
        'rows': {'BD': [1, 4, 8, 12, 15], 'SN': [5, 13], 'SH': [5, 13], 'OH': [8], 'CH': [1, 3, 5, 7, 9, 11, 13, 15]},
        'accents': [],
    },
    {
        'section': 'Hip Hop',
        'name': 'THE GROOVE',
        'variant': 'B',
        'rows': {'BD': [1, 4, 8, 12], 'SN': [5, 13], 'LT': [15, 16], 'MT': [12, 14], 'HT': [10, 11], 'OH': [8, 11, 12, 13, 15], 'CH': [1, 3, 5, 7, 9, 11, 13, 14], 'SH': [5, 13]},
        'accents': [],
    },
    {
        'section': 'Hip Hop',
        'name': 'BOOM BAP',
        'variant': None,
        'rows': {'BD': [1, 3, 6, 10, 14], 'SN': [3, 7, 11, 15], 'CL': [3, 7, 11, 15], 'CB': [9], 'OH': [15], 'CH': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16]},
        'accents': [1, 3, 5, 7, 9, 11, 13, 15],
    },
    {
        'section': 'Hip Hop',
        'name': 'MOST WANTED',
        'variant': 'A',
        'rows': {'BD': [1, 7, 9, 10, 16], 'SN': [5, 13], 'CL': [5, 13], 'CY': [1], 'CH': [1, 3, 5, 7, 9, 11, 13, 15]},
        'accents': [],
    },
    {
        'section': 'Hip Hop',
        'name': 'MOST WANTED',
        'variant': 'B',
        'rows': {'BD': [3, 7, 9, 10], 'SN': [5, 13], 'CL': [5, 13], 'OH': [3], 'CH': [1, 5, 7, 9, 11, 13, 15]},
        'accents': [],
    },
    {
        'section': 'Funk and Soul',
        'name': 'AMEN BREAK',
        'variant': 'A',
        'rows': {'BD': [1, 3, 11, 12], 'SN': [5, 8, 10, 13, 16], 'CH': [1, 3, 5, 7, 9, 11, 13, 15]},
        'accents': [],
    },
    {
        'section': 'Funk and Soul',
        'name': 'AMEN BREAK',
        'variant': 'B',
        'rows': {'BD': [1, 3, 11, 12], 'SN': [8, 10, 13, 16], 'RS': [5], 'CH': [1, 3, 5, 7, 9, 11, 13, 15]},
        'accents': [],
    },
    {
        'section': 'Funk and Soul',
        'name': 'AMEN BREAK',
        'variant': 'C',
        'rows': {'BD': [1, 3, 11], 'SN': [8, 10, 13, 16], 'RS': [15], 'CH': [1, 3, 5, 7, 9, 11, 13, 15]},
        'accents': [],
    },
    {
        'section': 'Funk and Soul',
        'name': 'AMEN BREAK',
        'variant': 'D',
        'rows': {'BD': [1, 3, 11], 'SN': [2, 5, 8, 10, 15], 'CY': [11], 'CH': [1, 3, 5, 7, 9, 13, 15]},
        'accents': [],
    },
    {
        'section': 'Funk and Soul',
        'name': 'THE FUNKY DRUMMER',
        'variant': None,
        'rows': {'BD': [1, 3, 7, 11, 14], 'SN': [5, 8, 10, 12, 13, 16], 'OH': [8, 14], 'CH': [1, 2, 3, 4, 5, 6, 7, 9, 10, 11, 12, 13, 15, 16]},
        'accents': [],
    },
    {
        'section': 'Funk and Soul',
        'name': 'IMPEACH THE PRESIDENT',
        'variant': None,
        'rows': {'BD': [1, 8, 9, 15], 'SN': [5, 13], 'OH': [11], 'CH': [1, 3, 5, 7, 8, 9, 13, 15]},
        'accents': [],
    },
    {
        'section': 'Funk and Soul',
        'name': 'WHEN THE LEVEE BREAKS',
        'variant': None,
        'rows': {'BD': [1, 2, 8, 11, 12], 'SN': [5, 13], 'CH': [1, 3, 5, 7, 9, 11, 13, 15]},
        'accents': [],
    },
    {
        'section': 'Funk and Soul',
        'name': 'THE BIG BEAT',
        'variant': None,
        'rows': {'BD': [1, 4, 7, 9], 'SN': [5, 13], 'CH': [5, 13]},
        'accents': [],
    },
    {
        'section': 'Funk and Soul',
        'name': "ASHLEY'S ROACHCLIP",
        'variant': None,
        'rows': {'BD': [1, 3, 7, 9, 10], 'SN': [5, 13], 'CB': [1, 3, 5, 7, 9, 11, 13, 15], 'OH': [11], 'CH': [1, 3, 5, 7, 9, 13, 15]},
        'accents': [],
    },
    {
        'section': 'Funk and Soul',
        'name': 'PAPA WAS TOO',
        'variant': None,
        'rows': {'BD': [1, 8, 9, 11, 16], 'SN': [5, 13], 'CY': [5], 'CH': [5, 9, 11, 13, 15, 16]},
        'accents': [],
    },
    {
        'section': 'Funk and Soul',
        'name': 'SUPERSTITION',
        'variant': None,
        'rows': {'BD': [1, 5, 9, 13], 'SN': [5, 13], 'CH': [1, 3, 5, 7, 8, 9, 10, 11, 13, 15, 16]},
        'accents': [],
    },
    {
        'section': 'Funk and Soul',
        'name': 'CISSY STRUT',
        'variant': 'A',
        'rows': {'BD': [1, 4, 6, 10, 12, 13, 15], 'SN': [5, 8, 10, 11], 'CY': [13, 15]},
        'accents': [],
    },
    {
        'section': 'Funk and Soul',
        'name': 'CISSY STRUT',
        'variant': 'B',
        'rows': {'BD': [1, 4, 8, 10, 12, 13, 15], 'SN': [3, 6, 7, 9, 10]},
        'accents': [],
    },
    {
        'section': 'Funk and Soul',
        'name': 'CISSY STRUT',
        'variant': 'C',
        'rows': {'BD': [1, 5, 8, 10, 12, 13, 15], 'SN': [3, 5, 6, 7, 10], 'CY': [13, 15]},
        'accents': [],
    },
    {
        'section': 'Funk and Soul',
        'name': 'CISSY STRUT',
        'variant': 'D',
        'rows': {'BD': [1, 5, 8, 10, 12, 13, 15], 'SN': [1, 3, 6, 9, 10], 'CY': [13, 15]},
        'accents': [],
    },
    {
        'section': 'Funk and Soul',
        'name': 'HOOK AND SLING',
        'variant': 'A',
        'rows': {'BD': [1, 3, 10, 14, 15], 'SN': [5, 7, 8, 11, 13], 'CY': [1, 3, 4, 6, 9, 10, 12, 15]},
        'accents': [],
    },
    {
        'section': 'Funk and Soul',
        'name': 'HOOK AND SLING',
        'variant': 'B',
        'rows': {'BD': [15], 'SN': [1, 5, 6, 8, 11, 12, 15, 16], 'CY': [1, 2, 4, 7, 9, 10, 13, 15]},
        'accents': [],
    },
    {
        'section': 'Funk and Soul',
        'name': 'HOOK AND SLING',
        'variant': 'C',
        'rows': {'BD': [1, 2, 13, 14, 16], 'SN': [3, 5, 7, 8, 11, 12, 15], 'CY': [1, 3, 5, 6, 8, 10, 13, 14]},
        'accents': [],
    },
    {
        'section': 'Funk and Soul',
        'name': 'HOOK AND SLING',
        'variant': 'D',
        'rows': {'BD': [1, 3, 6, 12, 14, 15], 'SN': [5, 8, 11, 16], 'CY': [1, 3, 5, 6, 8]},
        'accents': [],
    },
    {
        'section': 'Funk and Soul',
        'name': 'KISSING MY LOVE',
        'variant': 'A',
        'rows': {'BD': [1, 2, 4, 12, 15], 'SN': [5, 8, 10, 13], 'CY': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]},
        'accents': [],
    },
    {
        'section': 'Funk and Soul',
        'name': 'KISSING MY LOVE',
        'variant': 'B',
        'rows': {'BD': [1, 2, 4, 12, 14], 'SN': [5, 8, 10, 13, 16], 'CY': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16]},
        'accents': [],
    },
    {
        'section': 'Funk and Soul',
        'name': 'KISSING MY LOVE',
        'variant': 'C',
        'rows': {'BD': [1, 2, 4, 11, 13, 14], 'SN': [5, 8, 10, 16], 'CY': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16]},
        'accents': [],
    },
    {
        'section': 'Funk and Soul',
        'name': 'KISSING MY LOVE',
        'variant': 'D',
        'rows': {'BD': [1, 4, 12, 15], 'SN': [5, 10, 13], 'CY': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]},
        'accents': [],
    },
    {
        'section': 'Funk and Soul',
        'name': 'KISSING MY LOVE',
        'variant': 'E',
        'rows': {'BD': [1, 12, 14], 'SN': [5, 8, 10, 13], 'CY': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]},
        'accents': [],
    },
    {
        'section': 'Funk and Soul',
        'name': 'LADY',
        'variant': 'A',
        'rows': {'BD': [1, 9, 12, 15], 'SN': [5, 6], 'CY': [3, 7]},
        'accents': [],
    },
    {
        'section': 'Funk and Soul',
        'name': 'LADY',
        'variant': 'B',
        'rows': {'BD': [1, 12, 15], 'SN': [5, 6, 9], 'CY': [3, 7]},
        'accents': [],
    },
    {
        'section': 'Funk and Soul',
        'name': 'KNOCKS ME OFF MY FEET',
        'variant': 'A',
        'rows': {'BD': [1, 3, 5, 8, 9, 11, 13, 16], 'SN': [5, 13], 'CY': [1, 3, 7, 8, 10, 11, 15]},
        'accents': [],
    },
    {
        'section': 'Funk and Soul',
        'name': 'THE THRILL IS GONE',
        'variant': None,
        'rows': {'BD': [8, 9, 11], 'SN': [1, 5, 9, 13], 'CY': [1, 3, 5, 7, 9, 11, 13, 15]},
        'accents': [],
    },
    {
        'section': 'Funk and Soul',
        'name': 'POP TECH',
        'variant': 'A',
        'rows': {'BD': [1], 'SN': [5, 13], 'CY': [1, 9]},
        'accents': [],
    },
    {
        'section': 'Funk and Soul',
        'name': 'POP TECH',
        'variant': 'B',
        'rows': {'BD': [2, 14, 15, 16], 'SN': [5, 13], 'CY': [1, 9]},
        'accents': [],
    },
    {
        'section': 'Funk and Soul',
        'name': 'YA MAMA',
        'variant': 'A',
        'rows': {'BD': [1, 9], 'CY': [5, 13]},
        'accents': [],
    },
    {
        'section': 'Funk and Soul',
        'name': 'YA MAMA',
        'variant': 'B',
        'rows': {'BD': [1, 8, 9], 'CY': [5, 13]},
        'accents': [],
    },
    {
        'section': 'Funk and Soul',
        'name': 'COLD SWEAT',
        'variant': 'A',
        'rows': {'BD': [1, 9, 11], 'SN': [5, 8, 15], 'CY': [1, 3, 5, 7, 9, 11, 13, 15]},
        'accents': [],
    },
    {
        'section': 'Funk and Soul',
        'name': 'COLD SWEAT',
        'variant': 'B',
        'rows': {'BD': [3, 9, 11, 15], 'SN': [2, 5, 8, 10, 13], 'CY': [1, 3, 5, 7, 9, 11, 13, 15]},
        'accents': [],
    },
    {
        'section': 'Funk and Soul',
        'name': 'I GOT YOU (I FEEL GOOD)',
        'variant': 'A',
        'rows': {'BD': [1, 11], 'SN': [5, 13], 'CY': [1, 3, 5, 7, 9, 11, 13, 15]},
        'accents': [],
    },
    {
        'section': 'Funk and Soul',
        'name': 'I GOT YOU (I FEEL GOOD)',
        'variant': 'B',
        'rows': {'BD': [3, 7, 11, 15], 'SN': [5, 13], 'CY': [1, 3, 5, 7, 9, 11, 13, 15]},
        'accents': [],
    },
    {
        'section': 'Funk and Soul',
        'name': 'THE SAME BLOOD',
        'variant': None,
        'rows': {'BD': [1, 2, 9, 10], 'SN': [4, 6, 7, 13, 14, 15], 'CY': [1, 3, 5, 7, 8, 9, 11, 12, 13, 15, 16]},
        'accents': [],
    },
    {
        'section': 'Funk and Soul',
        'name': 'GROOVE ME',
        'variant': None,
        'rows': {'BD': [1, 4, 5, 8, 9, 10, 12, 14, 16], 'SN': [5, 13], 'CY': [1, 3, 5, 7, 9, 11, 13, 15]},
        'accents': [],
    },
    {
        'section': 'Funk and Soul',
        'name': 'LOOK-KA PY PY',
        'variant': 'A',
        'rows': {'BD': [1, 4, 6, 11, 14, 15], 'SN': [2, 5, 8, 9, 11, 15], 'CY': [1, 3, 5, 7, 9, 11, 13, 15]},
        'accents': [],
    },
    {
        'section': 'Funk and Soul',
        'name': 'LOOK-KA PY PY',
        'variant': 'B',
        'rows': {'BD': [1, 4, 6, 8, 9, 11, 14, 15], 'SN': [2, 5, 6, 8, 9, 11, 15], 'CY': [1, 3, 5, 7, 9, 11, 13, 15]},
        'accents': [],
    },
    {
        'section': 'Funk and Soul',
        'name': 'USE ME',
        'variant': 'A',
        'rows': {'BD': [1, 5, 13], 'SN': [3, 5, 7, 8, 10, 11, 13, 15, 16], 'CY': [1, 3, 5, 6, 7, 8, 9, 10, 11, 13, 14, 15, 16]},
        'accents': [],
    },
    {
        'section': 'Funk and Soul',
        'name': 'USE ME',
        'variant': 'B',
        'rows': {'BD': [5, 8, 11, 13], 'SN': [2, 3, 5, 7, 8, 10, 11, 13, 15, 16], 'CY': [1, 2, 3, 5, 6, 7, 8, 9, 10, 11, 13, 14, 15, 16]},
        'accents': [],
    },
    {
        'section': 'Funk and Soul',
        'name': 'USE ME',
        'variant': 'C',
        'rows': {'BD': [1, 3, 6, 8, 9, 11, 12, 14, 16], 'SN': [5, 8, 10, 13, 16], 'CY': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16]},
        'accents': [],
    },
    {
        'section': 'Funk and Soul',
        'name': 'USE ME',
        'variant': 'D',
        'rows': {'BD': [1, 3, 6, 9, 10, 12, 14, 16], 'SN': [5, 8, 16], 'CY': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 12, 14, 16]},
        'accents': [],
    },
    {
        'section': 'Funk and Soul',
        'name': 'FUNKY PRESIDENT',
        'variant': None,
        'rows': {'BD': [1, 4, 8, 10, 11], 'SN': [5, 13], 'CY': [1, 3, 5, 7, 9, 11, 13, 15]},
        'accents': [],
    },
    {
        'section': 'Funk and Soul',
        'name': 'GET UP',
        'variant': 'A',
        'rows': {'BD': [1, 11, 15], 'SN': [5, 7, 8, 10, 13, 16], 'CY': [1, 3, 5, 7, 8, 9, 11, 13, 15, 16]},
        'accents': [],
    },
    {
        'section': 'Funk and Soul',
        'name': 'GET UP',
        'variant': 'B',
        'rows': {'BD': [1, 11, 15], 'SN': [5, 7, 8, 10, 13, 16], 'CY': [1, 3, 5, 7, 8, 9, 11, 13, 15]},
        'accents': [],
    },
    {
        'section': 'Funk and Soul',
        'name': 'EXPENSIVE SHIT',
        'variant': None,
        'rows': {'BD': [4, 7, 15], 'SN': [1, 2, 4, 6, 9, 10, 13, 14], 'CY': [1, 3, 4, 5, 7, 8, 9, 11, 12, 13, 15, 16]},
        'accents': [],
    },
    {
        'section': 'Funk and Soul',
        'name': 'CHUG CHUG CHUG-A-LUG',
        'variant': None,
        'rows': {'BD': [1, 4, 6, 8, 10, 12, 15], 'SN': [2, 3, 5, 8, 10, 11, 13], 'CY': [1, 3, 5, 6, 7, 9, 10, 11, 13, 15]},
        'accents': [],
    },
    {
        'section': 'Funk and Soul',
        'name': 'THE FEZ',
        'variant': 'A',
        'rows': {'BD': [1, 9], 'SN': [2, 4, 5, 6, 8, 10, 12, 13, 14, 16], 'CY': [3, 7, 11, 15]},
        'accents': [],
    },
    {
        'section': 'Funk and Soul',
        'name': 'THE FEZ',
        'variant': 'B',
        'rows': {'BD': [1, 9, 12, 15], 'SN': [2, 4, 5, 6, 8, 10, 12, 13, 14, 16], 'CY': [3, 7, 11, 15]},
        'accents': [],
    },
    {
        'section': 'Funk and Soul',
        'name': 'ROCK STEADY',
        'variant': None,
        'rows': {'BD': [3, 5, 8, 11, 13], 'SN': [2, 5, 6, 8, 10, 13, 14, 16], 'CY': [1, 3, 5, 7, 8, 9, 11, 13, 15, 16]},
        'accents': [],
    },
    {
        'section': 'Funk and Soul',
        'name': 'SYNTHETIC SUBSTITUTION',
        'variant': 'A',
        'rows': {'BD': [1, 3, 8, 10, 11, 12, 16], 'SN': [5, 9], 'CY': [1, 3, 5, 7, 9, 11, 13, 15]},
        'accents': [],
    },
    {
        'section': 'Funk and Soul',
        'name': 'SYNTHETIC SUBSTITUTION',
        'variant': 'B',
        'rows': {'BD': [1, 3, 8, 10, 11, 12, 16], 'SN': [5, 9], 'CY': [1, 3, 5, 7, 9, 11, 13, 15]},
        'accents': [3],
    },
    {
        'section': 'Funk and Soul',
        'name': "COW'D BELL",
        'variant': 'A',
        'rows': {'BD': [1, 4, 7, 8, 11, 12, 14, 16], 'SN': [2, 4, 5, 6, 8, 10, 12, 13, 14, 16], 'CB': [1, 3, 4, 5, 7, 8, 9, 11, 12, 13, 15, 16]},
        'accents': [],
    },
    {
        'section': 'Funk and Soul',
        'name': "COW'D BELL",
        'variant': 'B',
        'rows': {'BD': [1, 3, 4, 8, 9, 11, 12, 14, 16], 'SN': [2, 4, 5, 6, 8, 10, 12, 13, 14, 16], 'CB': [1, 3, 4, 5, 7, 8, 9, 11, 12, 13, 15, 16]},
        'accents': [],
    },
    {
        'section': 'Funk and Soul',
        'name': 'PALM GREASE',
        'variant': 'A',
        'rows': {'BD': [1, 9, 16], 'SN': [5, 8, 10, 13, 16], 'CY': [1, 2, 3, 4, 6, 7, 9, 11, 12, 14, 15]},
        'accents': [],
    },
    {
        'section': 'Funk and Soul',
        'name': 'PALM GREASE',
        'variant': 'B',
        'rows': {'BD': [3], 'SN': [2, 6, 15], 'CY': [1, 3, 11]},
        'accents': [11],
    },
    {
        'section': 'Funk and Soul',
        'name': 'O-O-H CHILD',
        'variant': 'A',
        'rows': {'BD': [1, 3, 9, 11, 12], 'SN': [2, 4, 5, 7, 8, 10, 12, 13, 14, 16], 'CY': [1, 2, 3, 5, 6, 7, 9, 10, 11, 13, 14, 15]},
        'accents': [3, 7, 11, 15],
    },
    {
        'section': 'Funk and Soul',
        'name': 'O-O-H CHILD',
        'variant': 'B',
        'rows': {'BD': [1, 3, 9, 11, 12], 'SN': [2, 4, 5, 7, 8, 10, 13, 15], 'CY': [1, 2, 3, 5, 6, 7, 9, 10, 11, 13, 14, 15]},
        'accents': [3, 7, 11, 15],
    },
    {
        'section': 'Funk and Soul',
        'name': 'LADY MARMALADE',
        'variant': 'A',
        'rows': {'BD': [1, 3, 7, 9, 15], 'SN': [5, 13], 'CY': [1, 3, 5, 7, 9, 11, 13, 15]},
        'accents': [],
    },
    {
        'section': 'Funk and Soul',
        'name': 'LADY MARMALADE',
        'variant': 'B',
        'rows': {'BD': [13], 'SN': [5, 9], 'CY': [1, 3, 5, 7, 9, 11, 13, 15]},
        'accents': [11],
    },
    {
        'section': 'Funk and Soul',
        'name': 'HOT SWEAT',
        'variant': 'A',
        'rows': {'BD': [1, 11], 'SN': [5, 8, 9, 10, 13, 15, 16], 'CY': [1, 3, 5, 7, 9, 11, 13, 15]},
        'accents': [],
    },
    {
        'section': 'Funk and Soul',
        'name': 'HOT SWEAT',
        'variant': 'B',
        'rows': {'BD': [3, 4, 11, 12, 15], 'SN': [2, 4, 5, 6, 8, 10, 12, 13, 14], 'CY': [1, 3, 4, 5, 7, 9, 11, 12, 13, 15]},
        'accents': [],
    },
    {
        'section': 'Funk and Soul',
        'name': 'HAITIAN DIVORCE',
        'variant': None,
        'rows': {'BD': [3, 5, 11, 13], 'SN': [2, 5, 7, 8, 10, 13, 15, 16], 'CY': [1, 2, 3, 5, 6, 7, 8, 9, 10, 11, 13, 14, 15, 16]},
        'accents': [3, 11],
    },
    {
        'section': 'Funk and Soul',
        'name': 'COME DANCING',
        'variant': 'A',
        'rows': {'BD': [1, 8, 9, 16], 'SN': [2, 3, 5, 6, 7, 10, 11, 13, 14, 15], 'CY': [1, 3, 5, 7, 9, 11, 13, 15]},
        'accents': [],
    },
    {
        'section': 'Funk and Soul',
        'name': 'COME DANCING',
        'variant': 'B',
        'rows': {'BD': [1, 3, 6, 8, 9, 16], 'SN': [2, 5, 6, 10, 13, 14, 15], 'CY': [1, 3, 5, 7, 9, 11, 13, 15]},
        'accents': [11],
    },
    {
        'section': 'Funk and Soul',
        'name': 'RESPECT YOURSELF',
        'variant': 'A',
        'rows': {'BD': [1, 5, 9, 13], 'SN': [5, 11, 13], 'CY': [1, 3, 5, 7, 9, 11, 13, 15]},
        'accents': [],
    },
    {
        'section': 'Funk and Soul',
        'name': 'RESPECT YOURSELF',
        'variant': 'B',
        'rows': {'BD': [1, 5, 9, 13], 'SN': [5, 9, 11, 13], 'CY': [1, 3, 5, 7, 9, 11, 13, 15]},
        'accents': [],
    },
    {
        'section': 'Funk and Soul',
        'name': 'EXPRESS YOURSELF',
        'variant': 'A',
        'rows': {'BD': [1, 4, 9, 12, 15], 'SN': [5, 8, 10, 12, 14, 16], 'CY': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16]},
        'accents': [],
    },
    {
        'section': 'Funk and Soul',
        'name': 'EXPRESS YOURSELF',
        'variant': 'B',
        'rows': {'BD': [1, 4, 9, 12, 15], 'SN': [5, 8, 10, 12, 13], 'CY': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16]},
        'accents': [16],
    },
    {
        'section': 'Funk and Soul',
        'name': 'LET A WOMAN BE A WOMAN',
        'variant': None,
        'rows': {'BD': [3, 9, 11, 12, 14, 15], 'SN': [5, 8, 10, 11, 13, 14], 'CY': [1, 3, 5, 7, 9, 11, 13, 15]},
        'accents': [15],
    },
    {
        'section': 'Funk and Soul',
        'name': 'LET A MAN BE A MAN',
        'variant': None,
        'rows': {'BD': [3, 11, 15], 'SN': [5, 8, 10, 12, 13], 'CY': [1, 3, 5, 7, 9, 11, 13, 15]},
        'accents': [15],
    },
    {
        'section': 'Funk and Soul',
        'name': 'BOOKS OF MOSES',
        'variant': 'A',
        'rows': {'BD': [1, 5, 9, 12], 'SN': [5, 13], 'CY': [1, 3, 5, 7, 9, 11, 13, 15]},
        'accents': [],
    },
    {
        'section': 'Funk and Soul',
        'name': 'BOOKS OF MOSES',
        'variant': 'B',
        'rows': {'BD': [1, 5, 9], 'SN': [5, 13], 'CY': [1, 3, 5, 7, 9, 11, 13, 15]},
        'accents': [],
    },
    {
        'section': 'Funk and Soul',
        'name': 'MOTHER POPCORN',
        'variant': 'A',
        'rows': {'BD': [1, 3, 11], 'SN': [5, 8, 10, 15], 'CY': [1, 5, 9, 13]},
        'accents': [],
    },
    {
        'section': 'Funk and Soul',
        'name': 'MOTHER POPCORN',
        'variant': 'B',
        'rows': {'BD': [3, 7, 11, 15], 'SN': [2, 4, 5, 6, 8, 10, 12, 13, 14, 16], 'CY': [1, 5, 9, 13]},
        'accents': [],
    },
    {
        'section': 'Funk and Soul',
        'name': 'STRT BTS',
        'variant': 'A',
        'rows': {'BD': [1, 4, 7, 11], 'SN': [2, 5, 8, 12, 13], 'CY': [2, 3, 5, 6, 8, 9, 14, 15]},
        'accents': [9],
    },
    {
        'section': 'Funk and Soul',
        'name': 'STRT BTS',
        'variant': 'B',
        'rows': {'BD': [1, 4, 7, 11], 'SN': [2, 5, 8, 13], 'CY': [2, 3, 5, 6, 8, 9, 14, 15]},
        'accents': [9],
    },
    {
        'section': 'Funk and Soul',
        'name': "I GOT THE FEELIN'",
        'variant': 'A',
        'rows': {'BD': [1, 3, 11], 'SN': [7, 10, 15], 'CY': [1, 3, 5, 7, 9, 11, 13, 15]},
        'accents': [3, 11],
    },
    {
        'section': 'Funk and Soul',
        'name': "I GOT THE FEELIN'",
        'variant': 'B',
        'rows': {'BD': [3, 9, 13, 15], 'SN': [2, 5, 6, 8, 10, 11, 12, 14, 15, 16], 'CY': [1, 3, 5, 7, 9, 11, 13, 15]},
        'accents': [9],
    },
    {
        'section': 'Funk and Soul',
        'name': 'MORE BOUNCE TO THE OUNCE',
        'variant': None,
        'rows': {'BD': [1, 9, 10], 'SN': [5, 13], 'CL': [5, 13], 'OH': [1], 'CH': [3, 5, 7, 9, 11, 13, 15]},
        'accents': [],
    },
    {
        'section': 'Afro-Cuban',
        'name': 'SON CLAVE',
        'variant': None,
        'rows': {'BD': [1, 4, 5, 8, 9, 12, 13, 16], 'RS': [1, 4, 7, 11, 13], 'CY': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16]},
        'accents': [],
    },
    {
        'section': 'Afro-Cuban',
        'name': 'RUMBA',
        'variant': None,
        'rows': {'BD': [1, 4, 5, 8, 9, 12, 13, 16], 'RS': [1, 4, 8, 11, 13], 'CY': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16]},
        'accents': [],
    },
    {
        'section': 'Afro-Cuban',
        'name': 'BOSSA NOVA',
        'variant': None,
        'rows': {'BD': [1, 4, 5, 8, 9, 12, 13, 16], 'RS': [1, 4, 7, 11, 14], 'CY': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16]},
        'accents': [],
    },
    {
        'section': 'Afro-Cuban',
        'name': 'BOUTON',
        'variant': None,
        'rows': {'BD': [1, 9, 11, 15], 'RS': [4, 7, 13], 'CH': [1, 3, 4, 5, 7, 9, 11, 13, 15]},
        'accents': [],
    },
    {
        'section': 'Afro-Cuban',
        'name': 'GAHU',
        'variant': None,
        'rows': {'BD': [1, 5, 9, 13, 15], 'RS': [3, 4, 7, 8, 11, 12, 15, 16], 'CB': [1, 4, 7, 11, 15]},
        'accents': [],
    },
    {
        'section': 'Afro-Cuban',
        'name': 'SHIKO',
        'variant': None,
        'rows': {'BD': [1, 5, 7, 9, 13, 15], 'RS': [3, 4, 7, 8, 11, 12, 15, 16], 'CB': [1, 5, 7, 11, 13]},
        'accents': [],
    },
    {
        'section': 'Afro-Cuban',
        'name': 'SOUKOUS',
        'variant': None,
        'rows': {'BD': [1, 5, 9, 13, 15], 'RS': [1, 4, 7, 9, 12, 15], 'CB': [1, 4, 7, 10, 11]},
        'accents': [],
    },
    {
        'section': 'Drum and Bass',
        'name': 'DRUM AND BASS 1',
        'variant': 'A',
        'rows': {'BD': [1, 4, 8, 10, 11, 16], 'SN': [5, 13], 'CH': [1, 3, 5, 7, 9, 11, 13, 15]},
        'accents': [],
    },
    {
        'section': 'Drum and Bass',
        'name': 'DRUM AND BASS 1',
        'variant': 'B',
        'rows': {'BD': [1, 3, 8, 9, 10, 11], 'SN': [5, 13], 'CH': [1, 3, 5, 7, 9, 11, 13, 15]},
        'accents': [],
    },
    {
        'section': 'Drum and Bass',
        'name': 'DRUM AND BASS 2',
        'variant': 'A',
        'rows': {'BD': [1, 8, 10, 12, 16], 'SN': [5, 13], 'CH': [1, 3, 5, 7, 9, 11, 13, 15]},
        'accents': [],
    },
    {
        'section': 'Drum and Bass',
        'name': 'DRUM AND BASS 2',
        'variant': 'B',
        'rows': {'BD': [1, 12], 'SN': [5, 13], 'CH': [1, 3, 5, 7, 9, 11, 13, 15, 16]},
        'accents': [],
    },
    {
        'section': 'Drum and Bass',
        'name': 'DRUM AND BASS 3',
        'variant': None,
        'rows': {'BD': [1, 11], 'SN': [5, 13], 'OH': [7, 8, 9, 10], 'CH': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16]},
        'accents': [],
    },
    {
        'section': 'Drum and Bass',
        'name': 'DRUM AND BASS 4',
        'variant': 'A',
        'rows': {'BD': [1, 7], 'SN': [5, 11, 13], 'OH': [1], 'CH': [1, 3, 5, 7, 9, 11, 13, 15]},
        'accents': [],
    },
    {
        'section': 'Drum and Bass',
        'name': 'DRUM AND BASS 4',
        'variant': 'B',
        'rows': {'BD': [5, 11], 'SN': [5, 13], 'CH': [1, 3, 5, 7, 9, 11, 13, 15]},
        'accents': [],
    },
    {
        'section': 'Drum and Bass',
        'name': 'JUNGLE',
        'variant': 'A',
        'rows': {'BD': [1, 3, 11], 'SN': [5, 8, 10, 15], 'OH': [1], 'CH': [1, 3, 5, 7, 9, 11, 13, 15]},
        'accents': [],
    },
    {
        'section': 'Drum and Bass',
        'name': 'JUNGLE',
        'variant': 'B',
        'rows': {'BD': [2, 3, 11], 'SN': [2, 5, 8, 10, 15], 'CH': [1, 3, 5, 7, 9, 11, 13, 15]},
        'accents': [],
    },
    {
        'section': 'EDM',
        'name': 'TECHNO',
        'variant': None,
        'rows': {'BD': [1, 5, 9, 13, 15], 'SN': [5, 13], 'OH': [3, 7, 11, 15], 'CH': [10]},
        'accents': [],
    },
    {
        'section': 'EDM',
        'name': 'DUBSTEP',
        'variant': 'A',
        'rows': {'BD': [1, 11], 'SN': [9], 'OH': [5, 14], 'CH': [2, 3, 7, 12, 15]},
        'accents': [],
    },
    {
        'section': 'EDM',
        'name': 'DUBSTEP',
        'variant': 'B',
        'rows': {'BD': [1, 4, 7, 11], 'SN': [9], 'OH': [5, 14], 'CH': [2, 3, 7, 12, 15]},
        'accents': [],
    },
    {
        'section': 'EDM',
        'name': 'DUBSTEP - RATCHETED',
        'variant': None,
        'rows': {'BD': [1, 4, 9, 12], 'SN': [5, 13, 16], 'OH': [7], 'CH': [1, 2, 6, 7, 8, 9, 10, 12, 13, 14, 16]},
        'accents': [],
    },
    {
        'section': 'EDM',
        'name': 'UK GARAGE',
        'variant': 'A',
        'rows': {'BD': [1, 11], 'MT': [6, 12], 'CL': [5, 13], 'RS': [2, 8, 14], 'CH': [3, 4, 7, 11, 15, 16]},
        'accents': [],
    },
    {
        'section': 'EDM',
        'name': 'UK GARAGE',
        'variant': 'B',
        'rows': {'BD': [1, 11], 'MT': [6, 12], 'CL': [5, 13], 'RS': [8, 14], 'CH': [3, 7, 11, 15]},
        'accents': [],
    },
    {
        'section': 'EDM',
        'name': 'SYNTH WAVE',
        'variant': None,
        'rows': {'BD': [1, 9], 'SN': [5, 13], 'OH': [14], 'CH': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16]},
        'accents': [],
    },
    {
        'section': 'Dub',
        'name': 'HALF DROP',
        'variant': None,
        'rows': {'BD': [1], 'SN': [9], 'CH': [1, 3, 5, 7, 9, 11, 13, 15]},
        'accents': [],
    },
    {
        'section': 'Dub',
        'name': 'ONE DROP',
        'variant': None,
        'rows': {'BD': [9], 'SN': [9], 'CH': [1, 3, 5, 7, 9, 11, 13, 15]},
        'accents': [],
    },
    {
        'section': 'Dub',
        'name': 'TWO DROP',
        'variant': None,
        'rows': {'BD': [1, 9], 'SN': [9], 'CH': [1, 3, 5, 7, 9, 11, 13, 15]},
        'accents': [],
    },
    {
        'section': 'Dub',
        'name': 'STEPPERS',
        'variant': None,
        'rows': {'BD': [1, 5, 9, 13], 'SN': [9], 'CH': [1, 3, 5, 7, 9, 11, 13, 15]},
        'accents': [],
    },
    {
        'section': 'Reggaeton',
        'name': 'REGGAETON 1',
        'variant': None,
        'rows': {'BD': [1, 5, 9, 13], 'SN': [4, 7, 12, 15], 'CH': [1, 3, 5, 7, 9, 11, 13, 15]},
        'accents': [],
    },
    {
        'section': 'Reggaeton',
        'name': 'REGGAETON 2',
        'variant': None,
        'rows': {'BD': [1, 8], 'SN': [4, 6, 7, 8, 11, 12, 15], 'CH': [3, 7, 11, 15]},
        'accents': [6, 11],
    },
    {
        'section': 'Reggaeton',
        'name': 'REGGAETON 3',
        'variant': 'A',
        'rows': {'BD': [1, 9], 'SN': [1, 4, 7, 9, 12, 15]},
        'accents': [],
    },
    {
        'section': 'Reggaeton',
        'name': 'REGGAETON 3',
        'variant': 'B',
        'rows': {'BD': [1, 9], 'SN': [1, 4, 7, 9, 12, 15], 'CH': [1, 4, 7, 9, 12, 15]},
        'accents': [],
    },
    {
        'section': 'Pop',
        'name': 'POP 1',
        'variant': 'A',
        'rows': {'BD': [1, 2, 4, 8, 11], 'SN': [5, 13], 'CL': [5, 13], 'RS': [1, 2, 4, 7, 8, 11, 12], 'OH': [1, 4, 7, 9, 10], 'CH': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16]},
        'accents': [],
    },
    {
        'section': 'Pop',
        'name': 'IN THE AIR LAST NIGHT',
        'variant': 'A',
        'rows': {'BD': [11], 'SN': [13], 'HT': [3, 7], 'OH': [1, 13], 'CH': [3, 7, 11, 13]},
        'accents': [5, 13],
    },
    {
        'section': 'Pop',
        'name': 'IN THE AIR LAST NIGHT',
        'variant': 'B',
        'rows': {'BD': [1, 3, 5, 7, 9, 11, 15], 'SN': [13], 'HT': [3, 7], 'OH': [1, 13], 'CH': [3, 7, 11, 13]},
        'accents': [5, 13],
    },
    {
        'section': 'Pop',
        'name': 'NINETEEN',
        'variant': 'A',
        'rows': {'BD': [1, 2, 4, 8, 11], 'CL': [5, 13], 'RS': [1, 2, 4, 7, 8, 11, 12], 'OH': [1, 4, 7, 9, 10], 'CH': [1, 4, 7, 9, 10]},
        'accents': [],
    },
    {
        'section': 'Pop',
        'name': 'BLEU MONDAY',
        'variant': 'A',
        'rows': {'BD': [1, 9], 'SN': [5, 13], 'CL': [5, 13], 'OH': [3, 7, 11, 15]},
        'accents': [],
    },
    {
        'section': 'Pop',
        'name': 'BLEU MONDAY',
        'variant': 'B',
        'rows': {'BD': [1, 9], 'SN': [5, 13], 'CL': [5, 13], 'OH': [3, 7, 11, 15], 'CH': [1, 4, 5, 8, 9, 12, 13, 16]},
        'accents': [],
    },
    {
        'section': 'Breaks',
        'name': 'STANDARD BREAKBEAT 1',
        'variant': None,
        'rows': {'BD': [1, 11], 'SN': [5, 13]},
        'accents': [],
    },
    {
        'section': 'Breaks',
        'name': 'STANDARD BREAKBEAT 2',
        'variant': None,
        'rows': {'BD': [1, 3, 11], 'SN': [5, 13]},
        'accents': [],
    },
    {
        'section': 'Breaks',
        'name': 'STANDARD BREAKBEAT 3',
        'variant': None,
        'rows': {'BD': [1, 3, 7, 11], 'SN': [5, 8, 10, 13]},
        'accents': [],
    },
    {
        'section': 'Breaks',
        'name': 'POLYRHYTHMIC',
        'variant': 'A',
        'rows': {'BD': [1, 7], 'SN': [3, 5, 9, 11, 12, 13, 15, 16]},
        'accents': [5, 9, 13],
    },
    {
        'section': 'Breaks',
        'name': 'POLYRHYTHMIC',
        'variant': 'B',
        'rows': {'BD': [3, 9], 'SN': [5, 7, 11, 13]},
        'accents': [7, 13],
    },
    {
        'section': 'Breaks',
        'name': 'HYBRID KICK',
        'variant': None,
        'rows': {'BD': [1, 9], 'SN': [5, 13]},
        'accents': [],
    },
    {
        'section': 'Breaks',
        'name': 'HYBRID 8',
        'variant': 'A',
        'rows': {'BD': [1, 9, 11], 'SN': [5, 13]},
        'accents': [],
    },
    {
        'section': 'Irregular Breaks',
        'name': 'IRREGULAR 1',
        'variant': 'A',
        'rows': {'BD': [1, 3, 4, 7, 11], 'SN': [5, 8, 13, 16]},
        'accents': [],
    },
    {
        'section': 'Irregular Breaks',
        'name': 'IRREGULAR 1',
        'variant': 'B',
        'rows': {'BD': [1, 3, 8, 11], 'SN': [5, 13, 16]},
        'accents': [16],
    },
    {
        'section': 'Irregular Breaks',
        'name': 'IRREGULAR 2',
        'variant': 'A',
        'rows': {'BD': [1, 8, 11], 'SN': [4, 13]},
        'accents': [],
    },
    {
        'section': 'Irregular Breaks',
        'name': 'IRREGULAR 2',
        'variant': 'B',
        'rows': {'BD': [1, 3, 7, 11], 'SN': [5, 9, 13]},
        'accents': [],
    },
    {
        'section': 'Irregular Breaks',
        'name': 'IRREGULAR 3',
        'variant': None,
        'rows': {'BD': [1, 4, 9, 15], 'SN': [2, 5, 11, 14]},
        'accents': [],
    },
    {
        'section': 'Rolling Breaks',
        'name': 'ROLLING 1',
        'variant': None,
        'rows': {'BD': [1, 11], 'SN': [5, 13]},
        'accents': [5, 13],
    },
    {
        'section': 'Rolling Breaks',
        'name': 'ROLLING 3',
        'variant': 'A',
        'rows': {'BD': [1, 7, 13], 'SN': [5, 11]},
        'accents': [],
    },
    {
        'section': 'Rolling Breaks',
        'name': 'ROLLING 3',
        'variant': 'B',
        'rows': {'BD': [1, 7, 13], 'SN': [5, 11, 15]},
        'accents': [],
    },
    {
        'section': 'Rolling Breaks',
        'name': 'ROLLING 4',
        'variant': 'A',
        'rows': {'BD': [1, 2], 'SN': [5, 13]},
        'accents': [5, 13],
    },
    {
        'section': 'Rolling Breaks',
        'name': 'ROLLING 4',
        'variant': 'B',
        'rows': {'BD': [1, 8, 10, 11], 'SN': [5, 13]},
        'accents': [5, 13],
    },
    {
        'section': 'Rolling Breaks',
        'name': 'ROLLING 5',
        'variant': 'A',
        'rows': {'BD': [1, 3, 11], 'SN': [5, 13]},
        'accents': [5, 13],
    },
    {
        'section': 'Rolling Breaks',
        'name': 'ROLLING 5',
        'variant': 'B',
        'rows': {'BD': [1, 4, 11], 'SN': [5, 13]},
        'accents': [5, 13],
    },
    {
        'section': 'Rolling Breaks',
        'name': 'ROLLING 6',
        'variant': 'A',
        'rows': {'BD': [1, 7, 12], 'SN': [5, 13]},
        'accents': [5, 13],
    },
    {
        'section': 'Rolling Breaks',
        'name': 'ROLLING 6',
        'variant': 'B',
        'rows': {'BD': [1, 3, 8, 11, 14], 'SN': [5, 13]},
        'accents': [5, 13],
    },
    {
        'section': 'Rolling Breaks',
        'name': 'ROLLING 7',
        'variant': 'A',
        'rows': {'BD': [1, 8, 9, 12], 'SN': [5, 13]},
        'accents': [5, 13],
    },
    {
        'section': 'Rolling Breaks',
        'name': 'ROLLING 7',
        'variant': 'B',
        'rows': {'BD': [1, 4, 8, 11], 'SN': [5, 13]},
        'accents': [5, 13],
    },
    {
        'section': 'Rolling Breaks',
        'name': 'ROLLING 7',
        'variant': 'C',
        'rows': {'BD': [1, 8, 11], 'SN': [5, 13]},
        'accents': [5, 13],
    },
    {
        'section': 'Rolling Breaks',
        'name': 'ROLLING 8',
        'variant': None,
        'rows': {'BD': [1, 8], 'SN': [5, 13]},
        'accents': [],
    },
    {
        'section': 'Rolling Breaks',
        'name': 'ROLLING 9',
        'variant': 'A',
        'rows': {'BD': [1, 9, 11], 'SN': [5, 13]},
        'accents': [5, 13],
    },
    {
        'section': 'Rolling Breaks',
        'name': 'ROLLING 9',
        'variant': 'B',
        'rows': {'BD': [1, 2, 9, 11], 'SN': [5, 13]},
        'accents': [5, 13],
    },
    {
        'section': 'Rolling Breaks',
        'name': 'ROLLING 10',
        'variant': None,
        'rows': {'BD': [1, 8, 12], 'SN': [5, 13]},
        'accents': [5, 13],
    },
    {
        'section': 'Rolling Breaks',
        'name': 'ROLLING 11',
        'variant': None,
        'rows': {'BD': [1, 6, 7, 10, 11], 'SN': [5, 13]},
        'accents': [5, 13],
    },
    {
        'section': 'Breaks - Snare',
        'name': 'CONTEMPORARY SNARE 1',
        'variant': 'A',
        'rows': {'BD': [1, 11], 'SN': [5, 10, 15]},
        'accents': [1, 5, 11, 15],
    },
    {
        'section': 'Breaks - Snare',
        'name': 'CONTEMPORARY SNARE 1',
        'variant': 'B',
        'rows': {'BD': [3, 11], 'SN': [7, 10, 13]},
        'accents': [3, 7, 11, 13],
    },
    {
        'section': 'Breaks - Snare',
        'name': 'CONTEMPORARY SNARE 2',
        'variant': 'A',
        'rows': {'BD': [1, 3, 11], 'SN': [5, 13]},
        'accents': [1, 5, 11, 13],
    },
    {
        'section': 'Breaks - Snare',
        'name': 'CONTEMPORARY SNARE 2',
        'variant': 'B',
        'rows': {'BD': [3, 11, 12], 'SN': [5, 10, 13]},
        'accents': [3, 5, 11, 13],
    },
    {
        'section': 'Breaks - Snare',
        'name': 'CONTEMPORARY SNARE 3',
        'variant': 'A',
        'rows': {'BD': [1, 7, 15], 'SN': [5, 11, 14, 16]},
        'accents': [1, 5, 7, 11],
    },
    {
        'section': 'Breaks - Snare',
        'name': 'CONTEMPORARY SNARE 3',
        'variant': 'B',
        'rows': {'BD': [1, 4, 7, 15], 'SN': [5, 11]},
        'accents': [1, 5, 7, 11],
    },
    {
        'section': 'Breaks - Snare',
        'name': 'UNCONVENTIONAL SNARE 1',
        'variant': 'A',
        'rows': {'BD': [1, 5, 11], 'SN': [9, 15]},
        'accents': [9, 15],
    },
    {
        'section': 'Breaks - Snare',
        'name': 'UNCONVENTIONAL SNARE 1',
        'variant': 'B',
        'rows': {'BD': [1, 7, 11], 'SN': [5, 13]},
        'accents': [5, 7, 11, 13],
    },
    {
        'section': 'Breaks - Snare',
        'name': 'UNCONVENTIONAL SNARE 2',
        'variant': 'A',
        'rows': {'BD': [1, 13], 'SN': [5, 9, 12]},
        'accents': [5, 9],
    },
    {
        'section': 'Breaks - Snare',
        'name': 'UNCONVENTIONAL SNARE 2',
        'variant': 'B',
        'rows': {'BD': [1, 5, 9, 11], 'SN': [8, 13]},
        'accents': [9, 13],
    },
    {
        'section': 'Breaks - Snare',
        'name': 'UNCONVENTIONAL SNARE 3',
        'variant': 'A',
        'rows': {'BD': [1, 7, 14], 'SN': [5, 11]},
        'accents': [5, 11],
    },
    {
        'section': 'Breaks - Snare',
        'name': 'UNCONVENTIONAL SNARE 4',
        'variant': 'A',
        'rows': {'BD': [1, 3, 7, 9], 'SN': [5, 11]},
        'accents': [5, 11],
    },
    {
        'section': 'Breaks - Snare',
        'name': 'UNCONVENTIONAL SNARE 4',
        'variant': 'B',
        'rows': {'BD': [3, 11], 'SN': [1, 5, 10, 13]},
        'accents': [5, 13],
    },
    {
        'section': 'Ghost Snares',
        'name': 'GHOST SNARE 1',
        'variant': 'A',
        'rows': {'SN': [5, 8, 10, 13, 16]},
        'accents': [5, 13],
    },
    {
        'section': 'Ghost Snares',
        'name': 'GHOST SNARE 1',
        'variant': 'B',
        'rows': {'SN': [5, 8, 10, 13]},
        'accents': [5, 13],
    },
    {
        'section': 'Ghost Snares',
        'name': 'GHOST SNARE 2',
        'variant': 'A',
        'rows': {'SN': [2, 5, 8, 13, 16]},
        'accents': [5, 13],
    },
    {
        'section': 'Ghost Snares',
        'name': 'GHOST SNARE 2',
        'variant': 'B',
        'rows': {'SN': [2, 5, 10, 13, 16]},
        'accents': [5, 13],
    },
    {
        'section': 'Breaks - Kick',
        'name': 'CONTEMPORARY KICK 1',
        'variant': 'A',
        'rows': {'BD': [1, 11], 'SN': [5, 15]},
        'accents': [],
    },
    {
        'section': 'Breaks - Kick',
        'name': 'CONTEMPORARY KICK 1',
        'variant': 'B',
        'rows': {'BD': [3, 8, 11], 'SN': [5, 13]},
        'accents': [],
    },
    {
        'section': 'Breaks - Kick',
        'name': 'CONTEMPORARY KICK 2',
        'variant': 'A',
        'rows': {'BD': [3, 8, 11], 'SN': [5, 10, 13]},
        'accents': [5, 13],
    },
    {
        'section': 'Breaks - Kick',
        'name': 'CONTEMPORARY KICK 2',
        'variant': 'B',
        'rows': {'BD': [3, 11, 14], 'SN': [5, 13]},
        'accents': [5, 13],
    },
    {
        'section': 'Breaks - Kick',
        'name': 'CONTEMPORARY KICK 4',
        'variant': None,
        'rows': {'BD': [1, 9], 'SN': [5, 11]},
        'accents': [],
    },
    {
        'section': 'Drum Rolls',
        'name': 'DRUM ROLL 1',
        'variant': None,
        'rows': {'LT': [15, 16], 'MT': [12, 13, 14], 'HT': [9, 10, 11], 'CY': [1], 'OH': [1]},
        'accents': [11, 14, 15],
    },
    {
        'section': 'Drum Rolls',
        'name': 'DRUM ROLL 2',
        'variant': None,
        'rows': {'BD': [13, 15], 'SN': [1, 3, 4, 5, 7, 9, 10, 11, 12]},
        'accents': [],
    },
    {
        'section': 'Drum Rolls',
        'name': 'DRUM ROLL 3',
        'variant': None,
        'rows': {'SN': [1, 2, 3, 5, 6, 7, 9, 11, 13, 14, 15, 16]},
        'accents': [],
    },
    {
        'section': 'Drum Rolls',
        'name': 'DRUM ROLL 4',
        'variant': None,
        'rows': {'BD': [1, 7, 13], 'SN': [4, 5, 8, 9, 16], 'CY': [1, 7, 13]},
        'accents': [],
    },
    {
        'section': 'Drum Rolls',
        'name': 'DRUM ROLL 5',
        'variant': None,
        'rows': {'LT': [13, 15], 'MT': [5, 9, 11], 'HT': [1]},
        'accents': [5],
    },
    {
        'section': 'Drum Rolls',
        'name': 'DRUM ROLL 7',
        'variant': None,
        'rows': {'SN': [1, 5, 9, 13], 'LT': [11, 12, 14], 'MT': [4, 7, 8], 'HT': [3]},
        'accents': [14],
    },
    {
        'section': 'Drum Rolls',
        'name': 'DRUM ROLL 8',
        'variant': None,
        'rows': {'SN': [1, 8, 13], 'LT': [15, 16], 'MT': [5, 9, 11, 12], 'HT': [3]},
        'accents': [5, 9, 15],
    },
    {
        'section': 'Drum Rolls',
        'name': 'DRUM ROLL 9',
        'variant': None,
        'rows': {'SN': [1, 2, 7, 9, 10], 'LT': [13, 15], 'MT': [5, 11], 'HT': [3]},
        'accents': [5, 13],
    },
    {
        'section': 'Drum Rolls',
        'name': 'DRUM ROLL 10',
        'variant': None,
        'rows': {'SN': [1, 2, 5, 6, 9, 10, 13, 14], 'LT': [15, 16], 'MT': [7, 8, 11, 12], 'HT': [3, 4]},
        'accents': [7, 8, 15],
    },
    {
        'section': 'Drum Rolls',
        'name': 'DRUM ROLL 11',
        'variant': None,
        'rows': {'BD': [3, 6, 9, 12], 'SN': [1, 4, 7, 10, 13], 'LT': [11, 15, 16], 'MT': [5, 8], 'HT': [2, 14]},
        'accents': [5, 11, 15],
    },
    {
        'section': 'Drum Rolls',
        'name': 'DRUM ROLL 12',
        'variant': None,
        'rows': {'BD': [5, 7], 'SN': [1, 2, 9, 13], 'LT': [12, 14, 15], 'MT': [11, 13], 'HT': [3, 10], 'CY': [5, 7]},
        'accents': [3, 12, 14],
    },
    {
        'section': 'Drum Rolls',
        'name': 'DRUM ROLL 13',
        'variant': None,
        'rows': {'BD': [3, 4, 7, 8, 11, 12, 15, 16], 'SN': [1, 5, 9, 13], 'LT': [14], 'MT': [6, 10], 'HT': [2]},
        'accents': [6],
    },
    {
        'section': 'Drum Rolls',
        'name': 'DRUM ROLL 14',
        'variant': None,
        'rows': {'LT': [1, 2, 3, 16], 'MT': [4, 5, 6, 7, 8, 9, 14, 15], 'HT': [10, 11, 12, 13]},
        'accents': [7, 8, 9, 13, 14],
    },
    {
        'section': 'Drum Rolls',
        'name': 'DRUM ROLL 15',
        'variant': None,
        'rows': {'SN': [1, 5, 9, 13], 'LT': [4, 8, 12, 16], 'HT': [2, 10]},
        'accents': [],
    },
    {
        'section': 'Drum Rolls',
        'name': 'DRUM ROLL 16',
        'variant': None,
        'rows': {'BD': [3, 5, 11, 15], 'SN': [1, 2, 7, 8, 13, 14], 'CY': [5, 11], 'CH': [3, 9, 15]},
        'accents': [],
    },
    {
        'section': 'Drum Rolls',
        'name': 'DRUM ROLL 17',
        'variant': None,
        'rows': {'SN': [1, 2, 5, 7, 8, 11, 13, 14, 15, 16], 'MT': [9, 10], 'HT': [3, 4], 'CY': [5, 11]},
        'accents': [],
    },
    {
        'section': 'Drum Rolls',
        'name': 'DRUM ROLL 18',
        'variant': None,
        'rows': {'BD': [3, 5, 9, 11, 15], 'SN': [1, 7], 'CY': [1, 7, 13]},
        'accents': [],
    },
    {
        'section': 'Drum Rolls',
        'name': 'DRUM ROLL 19',
        'variant': None,
        'rows': {'BD': [3, 5, 9, 11, 15], 'SN': [1, 2, 7, 8, 13, 14], 'CY': [3, 5, 9, 11, 15]},
        'accents': [],
    },
    {
        'section': 'Drum Rolls',
        'name': 'DRUM ROLL 20',
        'variant': None,
        'rows': {'BD': [2, 4, 6, 8, 10, 12, 13], 'SN': [1, 9, 11, 14], 'LT': [16], 'MT': [7, 15], 'HT': [3, 5], 'CY': [9]},
        'accents': [],
    },
]
if __name__ == "__main__":
    problems = []
    seen_keys = set()

    for p in PATTERNS:
        key = pattern_key(p)
        label = f"{p['name']} {p['variant'] or ''}".strip()

        if key in seen_keys:
            problems.append(f"[DUPLICATE KEY] {label}")
        seen_keys.add(key)

        all_steps = set()
        for instr, steps in p["rows"].items():
            for s in steps:
                if not (1 <= s <= 16):
                    problems.append(f"[BAD STEP] {label} {instr} step={s}")
            all_steps.update(steps)
        for s in p["accents"]:
            if not (1 <= s <= 16):
                problems.append(f"[BAD ACCENT STEP] {label} step={s}")
            elif s not in all_steps:
                # a floating accent -- no instrument hits alongside it.
                # legitimate, but must be documented in PATTERN_NOTES.
                if key not in PATTERN_NOTES:
                    problems.append(f"[FLOATING ACCENT, no note] {label} {s}")

    for key in PATTERN_NOTES:
        if key not in seen_keys:
            problems.append(f"[STALE NOTE] {key} -- no matching pattern")

    print(f"{len(PATTERNS)} patterns loaded, {len(PATTERN_NOTES)} notes.")
    if problems:
        print(f"problems: {len(problems)}")
        for prob in problems:
            print(" ", prob)
    else:
        print("problems: 0")
        print("All entries consistent.")
